title:            이상한 스터디 블로그
description:      이제 마음 놓고 화장실을 갈 수 있다. 
url:              http://krazyeom.github.io 
signoff:          krazyeom
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /blog 
#    external:     true
#  - name:         Email
#    url:          mailto:krazyeom@gmail.com
#    external:     true
#  - name:         GitHub
#    url:          http://github.com/krazyeom
#    external:     true
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/
